# Generated by Django 3.0.5 on 2020-04-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
